config/routes.rb
Tweetkey::Application.routes.draw do

  resources :slaviks

  resources :proposals

  match "/users" => "users#index"

  root :to => 'tweets#index'

  match '/tweets/rank'
  match '/tweets/favorites'
  
  resources :tweets do
    resources :comments
  end

  resources :categories
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match '/:type' => "tweets#index" 

end

app/models/tweet.rb
class Tweet
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :description, type: String
  field :author, type: String
  field :category_id, type: String
  field :rank, type: Integer, default: "0"
  field :voter_up, type: Array, default: []
  field :voter_down, type: Array, default: []
  field :in_favorites, type: Array, default: []

  validates_presence_of :hotkey, :description, :category 

  belongs_to :category
  belongs_to :user

  embeds_many :comments

  scope :best, order_by(:rank => :desc)

  def favorites(user, todo)
    @author = User.where(:email => author).to_a
    if todo == "remove"
      self.in_favorites.delete(user.id)
      @author[0].karma -= 10
      user.favorites.delete(self.id)
    else
      self.in_favorites << user.id
      user.favorites << self.id
      @author[0].karma += 10
    end
    self.save
    @author[0].save
    user.save
    self.in_favorites.count
  end

  def vote(user, author, rate)
    @author = User.where(:email => author).to_a
    if self.voter_up.include?(user.id)
      if rate == "up"
        self.voter_up.delete(user.id)
        @author[0].karma -= 5
        self.rank -= 1
      else rate == "down"
        self.voter_down << user.id
        self.voter_up.delete(user.id)
        @author[0].karma -= 7
        self.rank -= 2
        user.karma -= 1
      end
    elsif self.voter_down.include?(user.id)
      if rate == "down"
        self.voter_down.delete(user.id)
        @author[0].karma += 2
        user.karma += 1
        self.rank += 1
      else rate == "up"
        self.voter_down.delete(user.id)
        self.voter_up << user.id
        @author[0].karma += 7
        self.rank += 2
      end
    else
      if rate == "up"
        self.voter_up << user.id
        @author[0].karma += 5
        self.rank += 1
      else
        self.voter_down << user.id
        @author[0].karma -= 2
        self.rank -= 1
        user.karma -= 1
      end
    end 
    self.save
    @author[0].save
    user.save
  end
  logger.debug @author
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  #before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @tweets = Tweet.page(params[:page]).per(2) unless params[:type]
    @tweets = Tweet.best.page(params[:page]).per(2) if params[:type] == "best"
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create!(params[:tweet])
    if @tweet.save
      redirect_to :action => "show", :id => @tweet
    else
      render action: "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    if user_signed_in?
      @todo = @tweet.in_favorites.include?(current_user.id) ? "remove" : "add"
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update_attributes(params[:tweet])
      redirect_to tweet_path(@tweet)
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :ok }
    end
  end

  def rank
    @tweet = Tweet.find(params[:id])
    @author = @tweet.author
      @tweet.vote(current_user, @author, params[:rate]) 
    respond_to do |format|
      format.js
    end
  end

  def favorites
    respond_to do |format|
      format.json { render :json => Tweet.find(params[:id]).favorites(current_user, params[:todo]) }
    end
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  = f.label :Category
  = f.collection_select :category, Category.all, :id, :name, :prompt => true
  %br
  = f.label :Name
  %br
  = f.text_field :name
  %br
  = f.label :Description
  %br 
  = f.text_area :description
  %br
  = hidden_field :tweet, :author, :value => current_user.email
  = f.submit("Post")

app/views/tweets/_info.html.haml
= @tweet.rank
- if user_signed_in?
  - @class = @tweet.voter_up.include?(current_user.id) ? "used" : "not_used"
  = link_to "▲", {:controller => "tweets", :action => "rank", :id => @tweet, :rate => "up"}, :class => @class, :remote => true
  %br
  - @class = @tweet.voter_down.include?(current_user.id) ? "used" : "not_used"
  = link_to "▼", {:controller => "tweets", :action => "rank", :id => @tweet, :rate => "down"}, :class => @class, :remote => true
  %br

app/views/tweets/_tweet.html.haml
.post-134.listing.type-listing.status-publish.hentry.post
  .left
    #addlike134.vote
      %span.b_like_disable ▲
      %span.span_currentvote 
        = tweet.rank
      %span.b_like_disable ▼
  / Post Title Condition for Post Format
  %h3
    %a{:href => "http://templatic.com/demos/plusone/listing/sweet-serenity/"}
      = tweet.hotkey
  / Post Title Condition for Post Format
  .post-meta
    добавил
    %span.post-author
      %a{:href => "http://templatic.com/demos/plusone/author/saqib-4343/", :title => "Posts by Saqib"}
        =tweet.author
    %span.post-date
      = tweet.updated_at.to_s(:short)
    %span.post-category
      Категория:
      =link_to tweet.category.name, "/categories/#{tweet.category.name}"
  / post meta #end
  / Post Content Condition for Post Format
  .post-content
    = tweet.description
    %a.read_more{:href => "http://templatic.com/demos/plusone/listing/sweet-serenity/", :title => ""} Read More →
  .post-meta.clear-meta
    %span.post-category-none
      Категории:
      = succeed "." do
        %a{:href => "http://templatic.com/demos/plusone/lcategory/lifestyle/"} Lifestyle
    %span.single_comments
      %a.comments_popup_link{:href => "http://templatic.com/demos/plusone/listing/sweet-serenity/#respond", :title => "Comment on Sweet Serenity"} 0
    .post-share
      .addthis_toolbox.addthis_default_style
        %a.addthis_button_compact.sharethis.at300m{:href => "http://www.addthis.com/bookmark.php?v=250&username=xa-4c873bb26489d97f"}
          %span.at300bs.at15nc.at15t_compact>
          Поделиться
        .atclear
        .atclear
    %span.post-view
      Просмотров :
      %strong 912
    %span.single-website
      %a{:href => "http://templatic.com"} Сайт автора
  / post meta #end
  / Post Content Condition for Post Format

app/views/tweets/edit.html.haml
= render "form"

app/views/tweets/index.html.haml
= render @tweets
= paginate @tweets

app/views/tweets/index.js.haml
!= "$('ul.tabbernav').html('#{j render "shared/tabs"}').show();"
- unless params[:page]
  != "$('#loop_main').html('#{j render(@tweets)}').append('#{j paginate(@tweets)}');"
- else
  != "$('#loop_main').append('#{j render(@tweets)}').append('#{j paginate(@tweets)}');"
  != if "$(#span.next).length"
    != "$('.pagination').remove();"

app/views/tweets/new.html.haml
= render 'form'

app/views/tweets/rank.js.haml
!= "$('#rank').html('#{j (render :partial => 'info' )}')"

app/views/tweets/show.html.haml
#rank
  = render "info"
%br
= link_to "Favorites", {:controller => "tweets", :action => "favorites", :id => @tweet, :todo => @todo}, :remote => true
%br
= render "comments/form"      
= link_to "Edit", :controller => "tweets", :action => "edit", :id => @tweet
|
= link_to "Home", tweets_path