config/routes.rb
Tweetkey::Application.routes.draw do

  resources :slaviks

  resources :proposals

  match "/users" => "users#index"

  root :to => 'tweets#index'

  match '/tweets/rank'
  match '/tweets/favorites'
  
  resources :tweets do
    resources :comments
  end

  resources :categories
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match '/:type' => "tweets#index" 

end

app/models/proposal.rb
class Proposal
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :title, type: String
  field :content, type: String

end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  def index
    @proposals = Proposal.all
  end

  def show
    @proposals = Proposal.find(params[:id])
  end

  def new
    @proposal = Proposal.new
  end

  def edit
    @proposals = Proposal.find(params[:id])
  end

  def create
    @proposals = Proposal.new(params[:proposal])
  end

  def update
    @proposals = Proposal.find(params[:id])
  end

  def destroy
    @proposals = Proposal.find(params[:id])
    @proposals.destroy
  end

end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.haml
= form_for(@proposal) do |f|
  .field
    = f.label :title
    %br/
    = f.text_field :title
    %br
  .field
    = f.label :content
    %br/
    = f.text_area :content
    %br
  .actions
    = f.submit

app/views/proposals/_proposal.html.haml
%table 
  - @proposal.each do |p|
    %tr
      %td
        %span.span_currentvote
      %td
        &nbsp;
      %td
        %h3
          =link_to p.content, "/proposals/#{p.id}"

app/views/proposals/edit.html.erb
<h1>Editing proposal</h1>

<%= render 'form' %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.haml
= render @proposals
= paginate @proposals if @proposals.exists?

app/views/proposals/index.js.haml
!= "$('ul.tabbernav').html('#{j render "shared/tabs"}').show();"
- unless params[:page]
  != "$('#loop_main').html('#{j render(@proposals)}').append('#{j paginate(@proposals) if @proposals.exists?}');"
- else
  != "$('#loop_main').append('#{j render(@proposals)}').append('#{j paginate(@proposals) if @proposals.exists?}');"
  != if "$(#span.next).length"
    != "$('.pagination').remove();"

app/views/proposals/new.html.erb
<h1>New proposal</h1>

<%= render 'form' %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/new.html.haml
= render 'form'

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_proposal_path(@proposal) %> |
<%= link_to 'Back', proposals_path %>